const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const url=pathToFileURL(path.join(__dirname,'../saa-c03-visual-handbook-2026.09.html')).href;
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox']}: {})});
 try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];
  page.on('pageerror',e=>errors.push(e.message));await page.goto(url);
  assert.equal(await page.locator('#revisionTools').count(),1,'Revision controls must be available');
  const walk=page.locator('.failover-walk');
  assert.equal(await walk.count(),1,'RDS must explain promotion and reconnection as separate stages');
  await walk.locator('summary').click();
  const motion=walk.locator('[data-walk-motion]');
  assert.equal(await motion.isChecked(),false,'Motion must be learner-enabled');
  assert.equal(await page.evaluate(()=>document.getAnimations().length),0,'No autoplay');
  assert.match(await walk.locator('[data-walk-status]').textContent(),/Healthy/);
  await walk.getByRole('button',{name:'Next step',exact:true}).click();
  assert.match(await walk.locator('[data-walk-status]').textContent(),/unavailable/);
  assert.equal(await walk.locator('[data-walk-node="writer"]').getAttribute('data-unavailable'),'true');
  assert.equal(await walk.locator('[data-walk-path="recovered"]').isVisible(),false);
  await walk.getByRole('button',{name:'Next step',exact:true}).click();
  assert.match(await walk.locator('[data-walk-status]').textContent(),/promotes/);
  assert.match(await walk.locator('[data-walk-standby-label]').textContent(),/Promoted writer/);
  assert.equal(await walk.locator('[data-walk-path="recovered"]').isVisible(),false,'Promotion alone must not depict a recovered client connection');
  await walk.getByRole('button',{name:'Next step',exact:true}).click();
  assert.match(await walk.locator('[data-walk-status]').textContent(),/re-establishes/);
  assert.equal(await walk.locator('[data-walk-path="recovered"]').isVisible(),true);
  assert.equal(await walk.getByRole('button',{name:'Next step',exact:true}).isDisabled(),true);
  await walk.getByRole('button',{name:'Replay',exact:true}).click();
  assert.match(await walk.locator('[data-walk-status]').textContent(),/Healthy/);
  await motion.check();
  await walk.getByRole('button',{name:'Next step',exact:true}).click();
  await walk.getByRole('button',{name:'Next step',exact:true}).click();
  await walk.getByRole('button',{name:'Next step',exact:true}).click();
  assert.ok(await walk.locator('svg').evaluate(el=>el.getAnimations({subtree:true}).length)>0,'Enabled motion traces the recovered path');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForFunction(()=>document.querySelector('[data-walk-motion]').disabled);
  assert.equal(await motion.isDisabled(),true);assert.equal(await motion.isChecked(),false);
  assert.equal(await walk.locator('svg').evaluate(el=>el.getAnimations({subtree:true}).length),0,'Changing OS preference cancels motion');
  assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');
  await walk.getByRole('button',{name:'Replay',exact:true}).click();
  for(let i=0;i<3;i++)await walk.getByRole('button',{name:'Next step',exact:true}).click();
  assert.match(await walk.locator('[data-walk-status]').textContent(),/re-establishes/);
  assert.equal(await page.evaluate(()=>document.getAnimations().length),0,'Reduced-motion mode retains the complete walkthrough');
  await page.emulateMedia({reducedMotion:'no-preference'});

  const data=await page.evaluate(()=>JSON.parse(document.getElementById('revisionData').textContent));
  assert.equal(data.questions.length,65);assert.equal(data.glossary.length,80);
  for(const q of data.questions){assert.ok(q.domain>=1&&q.domain<=4);assert.ok(q.answer.length);assert.equal(new Set(q.options).size,q.options.length);assert.ok(q.answer.every(i=>i<q.options.length));assert.ok(q.explain.length>50);}
  for(const q of data.questions.slice(0,20))assert.ok(!/(?:^|\.)\s*[A-E] [a-z]|^Answer: [A-E]/.test(q.explain.split('Variation:')[0]),'Shuffled feedback must identify options by meaning');
  assert.match(data.questions.find(q=>q.id==='practice-q08').explain,/Variation: A stable high-volume/);
  assert.match(data.questions.find(q=>q.id==='practice-q09').explain,/Variation: A correct network endpoint/);
  for(const entry of data.glossary)assert.ok(entry.cram.split(/\s+/).length<=25,entry.name);
  assert.equal(new Set(data.questions.map(q=>q.id)).size,65);
  for(const q of data.questions){
   const card=page.locator('[id="'+q.id+'"]');
   assert.equal(await card.locator('.core-layer > p').first().textContent(),q.q);
   assert.deepEqual(await card.locator('ol > li').allTextContents(),q.options,'Static study and scored quiz choices must stay aligned');
   const key=await card.locator('.answer strong').first().textContent();
   assert.equal(key,'Answer: '+q.answer.map(i=>String.fromCharCode(65+i)).join(', ')+'.');
  }
  assert.deepEqual(data.questions.reduce((counts,q)=>(counts[q.domain-1]++,counts),[0,0,0,0]),[20,17,15,13]);
  const clipped=await page.locator('.figure-node').evaluateAll(nodes=>nodes.filter(n=>{
   const r=n.querySelector('rect').getBBox(),t=n.querySelector('text').getBBox();
   return t.x<r.x+2||t.x+t.width>r.x+r.width-2||t.y<r.y||t.y+t.height>r.y+r.height;
  }).map(n=>n.getAttribute('data-node')));
  assert.deepEqual(clipped,[],'SVG labels must fit their nodes');
  const collisions=await page.locator('.interactive-figure svg').evaluateAll(svgs=>svgs.flatMap(svg=>{
   const labels=[...svg.querySelectorAll('.figure-edge text')].map(n=>({text:n.textContent,box:n.getBBox()}));const hits=[];
   const overlaps=(a,b)=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;
   for(let i=0;i<labels.length;i++)for(let j=i+1;j<labels.length;j++)if(overlaps(labels[i].box,labels[j].box))hits.push(labels[i].text+' / '+labels[j].text);
   for(const l of labels)for(const n of svg.querySelectorAll('.figure-node rect'))if(overlaps(l.box,n.getBBox()))hits.push(l.text+' / node');
   return hits;
  }));assert.deepEqual(collisions,[],'Arrow labels must not cover nodes or each other');
  const first=page.locator('[data-topic-id]').first();await first.locator('[data-confidence="green"]').click();
  assert.equal(await first.getAttribute('data-confidence'),'green');
  await page.locator('#weakOnly').check();assert.equal(await first.isVisible(),false);
  await page.reload();assert.equal(await first.getAttribute('data-confidence'),'green');
  await page.locator('#weakOnly').uncheck();await page.locator('#layerSelect').selectOption('cram');
  assert.equal(await first.locator('.core-layer').isVisible(),false);assert.equal(await first.locator('.cram-layer').isVisible(),true);
  await page.locator('#layerSelect').selectOption('deep');await page.locator('#expandAll').click();
  assert.equal(await page.locator('details.drill:not([open])').count(),0);await page.locator('#collapseAll').click();
  await page.locator('#layerSelect').selectOption('core');
  await page.locator('label[for="filter-domain-1"]').click();
  assert.equal(await page.locator('#revision-practice').isVisible(),false);
  await page.locator('#revisionTools a[href="#revision-practice"]').click();
  assert.equal(await page.locator('#revision-practice').isVisible(),true);
  const fig=page.locator('[data-figure="rds"]').first();await fig.locator('[data-node="instance-writer"]').click();
  assert.match(await fig.locator('.node-inspector').textContent(),/Distractor.*Cost/s);
  await fig.locator('select[data-failure]').selectOption('az-a');
  assert.ok(await fig.locator('[data-node="instance-writer"]').evaluate(n=>n.classList.contains('failed')));
  assert.ok(!await fig.locator('[data-node="instance-standby"]').evaluate(n=>n.classList.contains('failed')));
  await page.locator('[data-tree="compute"] [data-tree-choice="yes"]').click();
  assert.match(await page.locator('[data-tree="compute"]').textContent(),/EC2/);
  assert.equal(await page.locator('[data-tree="compute"]').evaluate(el=>el.contains(document.activeElement)),true);
  await page.locator('[data-tree="database"] [data-tree-choice="yes"]').click();
  assert.match(await page.locator('[data-tree="database"]').textContent(),/Redshift/);
  await page.locator('#quizSize').selectOption('5');await page.locator('#quizStart').click();
  assert.equal(await page.locator('#quizQuestion').isVisible(),true);
  await page.locator('#quizSubmit').click();assert.match(await page.locator('#quizFeedback').textContent(),/Select/);
  await page.locator('#quizOptions input').first().check();await page.locator('#quizSubmit').click();
  const answeredId=await page.locator('#quizQuestion').getAttribute('data-question');
  await page.locator('#quizFinish').click();assert.match(await page.locator('#quizResults').textContent(),/Domain 1/);
  assert.match(await page.locator('#quizResults').textContent(),/unanswered/i);
  await page.locator('#quizStart').click();
  for(let index=0;index<5;index++){
   const id=await page.locator('#quizQuestion').getAttribute('data-question');const q=data.questions.find(q=>q.id===id);
   for(const option of q.answer)await page.locator('#quizOptions input[value="'+option+'"]').check();
   await page.locator('#quizSubmit').click();assert.match(await page.locator('#quizFeedback').textContent(),/^Correct\./);
   if(index<4)await page.locator('#quizNext').click();
  }
  await page.locator('#quizFinish').click();assert.match(await page.locator('#quizResults').textContent(),/5 \/ 5 \(100%/);
  await page.locator('#quizStart').click();
  const badId=await page.locator('#quizQuestion').getAttribute('data-question'),bad=data.questions.find(q=>q.id===badId);
  const wrongIndex=bad.options.findIndex((_,i)=>!bad.answer.includes(i));
  const incorrect=[wrongIndex,...bad.answer.slice(1)];
  for(const option of incorrect)await page.locator('#quizOptions input[value="'+option+'"]').check();
  await page.locator('#quizSubmit').click();assert.match(await page.locator('#quizFeedback').textContent(),/^Incorrect\./);
  await page.locator('#quizFinish').click();assert.match(await page.locator('#quizResults').textContent(),/0 \/ 5/);
  await page.reload();await page.locator('#quizPile').selectOption('wrong');await page.locator('#quizStart').click();
  assert.equal(await page.locator('#quizLive').isVisible(),true);
  await page.evaluate(()=>{const real=Date.now;Date.now=()=>real()+1000000000;});
  await page.waitForFunction(()=>document.getElementById('quizLive').hidden);
  assert.match(await page.locator('#quizResults').textContent(),/Time expired/);await page.reload();
  await page.evaluate(()=>localStorage.setItem('aws-saa-revision-v1',JSON.stringify({confidence:{},wrong:[]})));
  await page.reload();await page.locator('#quizSize').selectOption('5');await page.locator('#quizStart').click();
  const timer=await page.locator('#quizTimer').textContent();await page.locator('#quizPile').selectOption('wrong');await page.locator('#quizStart').click();
  assert.match(await page.locator('#quizResults').textContent(),/No questions match/);
  await page.waitForFunction(before=>document.getElementById('quizTimer').textContent!==before,timer);
  await page.locator('#quizFinish').click();
  await page.locator('#flashReveal').click();assert.equal(await page.locator('#flashBack').isVisible(),true);
  await page.locator('#clueReveal').click();assert.equal(await page.locator('#clueAnswer').isVisible(),true);
  await page.locator('#search').fill('<img src=x onerror=alert(1)>');assert.equal(await page.locator('img[src="x"]').count(),0);
  await page.locator('#search').fill('');
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile page must not overflow');
  await page.screenshot({path:'/tmp/saa-revision-mobile.png',animations:'disabled'});
  await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/tmp/saa-revision-desktop.png',animations:'disabled'});
  await fig.screenshot({path:'/tmp/saa-revision-rds.png'});
  await page.emulateMedia({media:'print'});await page.evaluate(()=>dispatchEvent(new Event('beforeprint')));
  await page.evaluate(()=>document.documentElement.dataset.theme='dark');
  assert.equal(await page.locator('.interactive-figure').first().evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(244, 244, 244)');
  assert.equal(await first.locator('.core-layer').isVisible(),true);
  assert.equal(await page.locator('#revisionTools').isVisible(),false);
  assert.equal(await walk.locator('li').count(),4);
  for(const li of await walk.locator('li').all())assert.equal(await li.isVisible(),true,'Print preserves every stage');
  await page.pdf({path:'/tmp/saa-revision-print.pdf',format:'A4'});
  assert.deepEqual(errors,[]);
  const blocked=await browser.newContext();await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('Blocked');}}));
  const bp=await blocked.newPage();const be=[];bp.on('pageerror',e=>be.push(e.message));await bp.goto(url);
  await bp.locator('[data-confidence="green"]').first().click();assert.deepEqual(be,[]);await blocked.close();
  const corrupt=await browser.newContext();await corrupt.addInitScript(()=>localStorage.setItem('aws-saa-revision-v1','{broken'));
  const cp=await corrupt.newPage();const ce=[];cp.on('pageerror',e=>ce.push(e.message));await cp.goto(url);assert.deepEqual(ce,[]);await corrupt.close();
  console.log('Revision browser checks passed: content, confidence, filtering, layers, diagrams, trees, quiz, recall, storage, mobile and print.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
